services:
  marznode:
    build: .
    restart: always
    network_mode: host
    command: [ "sh", "-c", "sleep 10 && python3 marznode.py" ]

    environment:
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SING_BOX_EXECUTABLE_PATH: "/usr/local/bin/sing-box"
      HYSTERIA_EXECUTABLE_PATH: "/usr/local/bin/hysteria"
      SSL_CLIENT_CERT_FILE: "/var/lib/marznode/client.pem"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"

    volumes:
      - /var/lib/marznode:/var/lib/marznode
      - /var/log/xray:/var/log/xray
      - ./marznode/__init__.py:/app/marznode/__init__.py:ro
      - ./marznode/marznode.py:/app/marznode/marznode.py:ro
      - ./marznode/service/service.py:/app/marznode/service/service.py:ro
      - ./marznode/storage/devices.py:/app/marznode/storage/devices.py:ro
      - ./marznode/storage/__init__.py:/app/marznode/storage/__init__.py:ro
      - ./marznode/backends/xray/_runner.py:/app/marznode/backends/xray/_runner.py:ro
      - ./marznode/backends/xray/xray_backend.py:/app/marznode/backends/xray/xray_backend.py:ro
